outpath: /nfs/home/xutongqiao/pull-requests/ready-to-gem5/result
gem5_commit_id: 6204aeb
task_name: given-test
commit: 测试给定程序运行的情况
task_category: given
source: /nfs/home/xutongqiao/vector/TSVC_2/bin/riscv-GNU/tsvc_novec_default
# case_name: bwaves
# case_index: 37801
# spec: spec06

given: 
# coverage: 0.1
# type: float
kmh_version: v2
modify_functions:
  # - kmhv2fpreg
  # - kmhv2intreg
  - lifetimedb
modify_params:
  # kmhv2fpreg:    
  #   size: 256
  # kmhv2intreg:
  #   size: 224