outpath: /nfs/home/xutongqiao/feature/feature_auto/modify_test/
gem5_commit_id: 6204aeb
task_name: test
task_category: spec
spec: spec06
coverage: 0.1
type: float
kmh_version: v3
modify_functions:
  - kmhv3fpreg
  - kmhv3intreg
modify_params:
  kmhv3fpreg:
    size: 254
  kmhv3intreg:
    size: 224